### ISSUE TITLE
Tests (chapter 11) fail due to Meteor.userId() instead of this.userId

### ISSUE THREAD

**Issue by HildoBijl** [meteor/simple-todos#59]
In the tutorial, both in Blaze and React (I haven't checked Angular) in chapter 10 (listing 10.10 for Blaze and 10.12 for React) we introduce the line

`if (task.private && task.owner !== Meteor.userId()) {`

If I then go to chapter 11 (testing) and make the test task private by adding
          `private: true,`
in the added task, and then run the test, the test crashes. Here's the call stack.

`Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:252:19)
    at Object.tasksRemove (imports/api/tasks.js:39:31)
    at Test.<anonymous> (imports/api/tasks.tests.js:33:20)
    at run (packages/practicalmeteor:mocha-core/server.js:34:29)
    at Context.wrappedFunction (packages/practicalmeteor:mocha-core/server.js:63:33)
    at callFnAsync (C:\Users\Hildo\AppData\Local\.meteor\packages\practicalmeteor_mocha\2.4.5_6\npm\node_modules\mocha\lib\runnable.js:338:8)
    at Test.Runnable.run (C:\Users\Hildo\AppData\Local\.meteor\packages\practicalmeteor_mocha\2.4.5_6\npm\node_modules\mocha\lib\runnable.js:290:7)
    at Runner.runTest (C:\Users\Hildo\AppData\Local\.meteor\packages\practicalmeteor_mocha-core\1.0.1\npm\node_modules\mocha\lib\runner.js:422:10)
    at C:\Users\Hildo\AppData\Local\.meteor\packages\practicalmeteor_mocha-core\1.0.1\npm\node_modules\mocha\lib\runner.js:533:12`

Replacing `Meteor.userId()` by `this.userId` solves the issue. So I would recommend change all instances of `Meteor.userId()` into `this.userId` in the api/tasks.js file.

(I'm running a Windows 10 machine, and I'm running the command console using administrator privileges. Otherwise the tests won't run in the first place.)

**Comment by HildoBijl** [comment]
This appears to be a duplicate of [https://github.com/meteor/tutorials/issues/124].

**Comment by zetekla** [comment]
A simple fix is to go to `tasks.js` to replace `Meteor.userId()` with `this.userId` which 
is to use the this context of the function.

**Comment by BrianMulhall** [comment]
the tutorial has been updated to use this.userId in step 10.10 as was suggested
