### ISSUE TITLE
Testing: Update to Meteor 1.6 and newer

### ISSUE THREAD

**Issue by ghost** [meteor/simple-todos#60]
`practicalmeteor:mocha` throws a bunch of errors and Meteor 1.6+ seems to recommend `meteortesting:mocha`. Since the last one doesn't work with the code described in the tutorial, I switched to `cultofcoders:mocha` – a fork of the first one. This works if I remove `practicalmeteor:mocha` from the project.

You should update the tutorial with `meteortesting:mocha`, so new users don't run into these errors.

After using the working mocha package, another error occurs inside the test:

```
Error: Meteor.userId can only be invoked in method calls or publications.
    at AccountsServer.userId (packages/accounts-base/accounts_server.js:79:13)
    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:273:19)
    at Object.tasks.remove (imports/api/tasks.js:37:31)
    at Test.it (imports/api/tasks.tests.js:27:20)
    at run (packages/practicalmeteor:mocha-core/server.js:34:29)
    at Context.wrappedFunction (packages/practicalmeteor:mocha-core/server.js:63:33)
    at run (packages/practicalmeteor:mocha-core/server.js:52:15)
```

The line with `Meteor.server.method_handlers['tasks.remove']` does not seem to call the method as expected, or am I missing something?

**Comment by mikaelmello** [comment]
+1

**Comment by gabimoncha** [comment]
+1

**Comment by BrianMulhall** [comment]
this has been updated in the latest version of the step by step guide
